### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Benbbe**

### CODE REVIEW

**Comment by Benbbe** [comment]
Merge all

**Comment by Benbbe** [comment]
add all

**Comment by Benbbe** [comment]
add all

**Comment by Benbbe** [comment]
add all

**Comment by Benbbe** [comment]
add addl

**Comment by Benbbe** [comment]
add all

**Comment by miguelsimoni** [comment]
I'm closing the PR without merging it because it introduces some customizations that do not have to be in the theme template.

**Pull request closed without merging**
